services:

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: alam
      POSTGRES_PASSWORD: kosong
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-alam@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
#    environment:
#      - RABBITMQ_DEFAULT_USER=alam
#      - RABBITMQ_DEFAULT_PASS=kosong
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  postgres:
    external: true
    driver: bridge

volumes:
  postgres:
  pgadmin: